### ISSUE TITLE
Installing Error

### ISSUE THREAD

**Issue by sechix** [Glowforge/solidus_reffiliate#2]
It is ready? Because I get following error trying to install gem:
Git error: command `git clone
'https://bitbucket.org/glowforge/solidus_reffiliate'

**Comment by lizrush** [comment]
We've updated the README--the correct location is `https://github.com/Glowforge/solidus_reffiliate.git` (this repository). 

Although you are free to clone, your milage may vary! Breaking changes may occur.

**Comment by sechix** [comment]
Thanks !! but I have solidus 2.1 and give errors due to solidus_core version :(
